extends:
  - airbnb-typescript
  - airbnb/hooks
parserOptions:
  project: ./tsconfig.json
settings:
  import/resolver:
    typescript: {}
rules:
  '@typescript-eslint/type-annotation-spacing':
    - error
    - before: false
      after: true
  react/jsx-props-no-spreading: 'off'
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
